services:
  edges:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5005:5005'
      - '3000:3000'
    env_file:
      - .env
    networks:
      - edges

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
    networks:
      - edges

  postgres:
    image: postgres:15
    ports:
      - '5434:5432'
    env_file:
      - .env
    networks:
      - edges

networks:
  edges:
